---

-  hosts: CentOS
   become: true
   tasks:

   - name: Installing Nagios Libraries and Dependencies
     tags: centos, dependecies, libraries
     yum:
       name:
         - gcc
         - glibc
         - glibc-common
         - perl
         - httpd
         - php
         - wget
         - gd
         - gd-devel
         - openssl-devel
         - gcc
         - glibc
         - glibc-common
         - make
         - gettext
         - automake
         - autoconf
         - wget
         - openssl-devel
         - net-snmp
         - net-snmp-utils
         - python2-pip
       state: latest

   - name: Creating the Nagios Directory
     file:
       path: ~/nagios
       state: directory

   - name: Installation of Nagios
     unarchive:
       src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
       dest: ~/nagios
       remote_src: yes
       mode: 0777
       owner: root
       group: root

   - name: Installation of Nagios Plugins
     unarchive:
       src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
       dest: ~/nagios
       remote_src: yes
       mode: 0777
       owner: root
       group: root

   - name: Compilation, Installation and User Modification
     shell: |
       cd ~/nagios/nagioscore-**
       ./configure
       make all
       make install-groups-users
       usermod -a -G nagios apache
       make install
       make install-daemoninit
       make install-commandmode
       make install-config
       make install-webconf

   - name: Compilation and Installation of Plugins
     shell: |
       cd ~/nagios/nagios-plugins*
       ./tools/setup
       ./configure
       make
       make install

   - name: Adding a Password to the User/s
     community.general.htpasswd:
       path: /usr/local/nagios/etc/htpasswd.users
       name: admin
       password: admin

   - name: Enabling HTTPD
     service:
       name: httpd
       state: restarted
       enabled: true

   - name: Enabling Nagios
     service:
       name: nagios
       state: restarted
       enabled: true


