---

-  hosts: CentOS
   become: true
   tasks:

   - name: Disable SELinux on CentOS
     become: true
     shell:
       sudo sed -i 's/SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config

   - name: Installing nagios dependecies and libraries
     tags: centos, dependecies, libraries
     yum:
       name:
        - unzip
        - postfix
        - gcc
        - glibc
        - glibc-common
        - perl
        - httpd
        - php
        - wget
        - gd
        - gd-devel
        - openssl-devel
        - gcc
        - glibc
        - glibc-common
        - make
        - gettext
        - automake
        - autoconf
        - wget
        - openssl-devel
        - net-snmp
        - net-snmp-utils
        - python3-pip
        - python3
        - perl-devel
        - gcc-c++
        - libtool
        - httpd-tools
       state: latest

   - name: Add Nagios User
     user:
       name: nagios
       state: present

   - name: Add nagcmd Group
     group:
       name: nagcmd
       state: present

   - name: Add nagios to nagcmd
     user:
       name: nagios
       group: nagcmd
       append: yes

   - name: Create Nagios directory PATH
     file:
       path: ~/nagios
       state: directory

   - name: Download Nagios
     unarchive:
        src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
        dest: ~/nagios
        remote_src: yes
        mode: 0777
        owner: root
        group: root

   - name: Download Nagios plugins
     unarchive:
        src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
        dest: ~/nagios
        remote_src: yes
        mode: 0777
        owner: root
        group: root

   - name: Configure Nagios
     shell:
        cd ~/nagios
        ./configure --with-command-group=nagcmd

   - name: Compile and Install Nagios
     shell:
        cd ~/nagios
        make all
        make install
        make install-daemoninit
        make install-init
        make install-commandmode
        make install-config

   - name: Compile and Install Nagios plugins
     shell:
        cd ~/nagios/nagios-plugins*
        ./tools/setup
        ./configure
        make
        make install

   - name: Install Nagios Web Configuration
     shell:
         cd ~/nagios
         make install-webconf

   - name: Adding Users to Nagios
     community.general.htpasswd:
        path: /usr/local/nagios/etc/htpasswd.users
        name: admin
        password: admin

   - name: Start Apache
     service:
        name: httpd
        state: restarted
        enabled: yes

   - name: Start Nagios service
     service:
        name: nagios
        state: restarted
        enabled: yes
